require: rubocop-rspec

AllCops:
  NewCops: enable

Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Bundler/OrderedGems:
  Enabled: false
Metrics/BlockLength:
  Max: 55
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 20
Layout/LineLength:
  Max: 110
RSpec/ExampleLength:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
